# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
use_sim_time: true # To work with simulation

moveit_simple_controller_manager:
  controller_names:
    - scara_controller
    - gripper_controller

  scara_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - lower_link_joint
      - middle_link_joint
      - upper_link_joint
      - end_link_joint
      - wrist_link_joint
  gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - left_finger_link_joint
      - right_finger_link_joint
