# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true

    scara_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

scara_controller:
  ros__parameters:
    joints:
      - lower_link_joint
      - middle_link_joint
      - upper_link_joint
      - end_link_joint
      - wrist_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
gripper_controller:
  ros__parameters:
    joints:
      - left_finger_link_joint
      - right_finger_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
